apps/contacto/urls.py
# Python imports


# Django imports
from django.conf.urls import url


# Local imports
from .views import ContactanosView

# Create your tests here.


urlpatterns = [
    url(r'^$', ContactanosView.as_view(), name='index'),
]

apps/principal/urls.py
from django.conf.urls import url

from .views import IndexView, EntrevistaView, CarmenGitHubView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^entrevista/$', EntrevistaView.as_view(), name='entrevista'),
    url(r'^2016/$', CarmenGitHubView.as_view(), name='carmen'),
]

eligela/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.views.static import serve


from apps.principal import urls as principal_urls
from apps.contacto import urls as contacto_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(principal_urls,
                      namespace='principal',
                      app_name='principal'
                      )
        ),
    url(r'^contacto/', include(contacto_urls,
                               namespace='contacto',
                               app_name='contacto'
                               )
        ),
]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$',
                        serve,
                        {'document_root': settings.MEDIA_ROOT, }
                        ),
                    ]

apps/contacto/models.py
# Python imports


# Django imports
from django.db import models


# Local imports


class Colegio(models.Model):
    nombre = models.CharField(max_length=100)
    distrito = models.CharField(max_length=100)
    telefono = models.CharField(blank=True, max_length=9)
    direccion = models.CharField(max_length=100)
    asunto = models.TextField()

    def __str__(self):
        return self.nombre

apps/principal/models.py
from django.db import models
from stdimage import StdImageField
from embed_video.fields import EmbedVideoField


class Beneficio(models.Model):

    def image_path(self, filename):
        return "beneficios/{0}/{1}".format(self.descripcion[:50],
                                           str(filename))

    def beneficio_imagen_administrador(self):
        if not self.imagen:
            return None

        imagenHTML = '<img src="/media/{0}" style="width: 150px" />'.format(
            self.imagen)

        return imagenHTML

    beneficio_imagen_administrador.allow_tags = True

    descripcion = models.TextField()
    imagen = StdImageField(upload_to=image_path)

    def __str__(self):
        return self.descripcion


class Colaborador(models.Model):

    def image_path(self, filename):
        return "beneficios/{0}/{1}".format(self.nombre, str(filename))

    def colaborador_imagen_administrador(self):
        if not self.imagen:
            return None

        imagenHTML = '<img src="/media/{0}" style="width: 75px" />'.format(
            self.imagen
        )

        if ('.jpg' in imagenHTML):
            return imagenHTML.replace('.jpg', '.miniatura.jpg')
        elif ('.jpeg' in imagenHTML):
            return imagenHTML.replace('.jpeg', '.miniatura.jpeg')
        elif ('.png' in imagenHTML):
            return imagenHTML.replace('.png', '.miniatura.png')
        elif ('.gif' in imagenHTML):
            return imagenHTML.replace('.gif', '.miniatura.gif')
        else:
            return imagenHTML

    colaborador_imagen_administrador.allow_tags = True

    imagen = StdImageField(upload_to=image_path,
                           variations={
                               'miniatura': (75, 75)
                           }
                           )
    link = models.URLField()
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'colaboradores'


class Carrera(models.Model):
    def image_path(self, filename):
        return "carreras/{0}/{1}".format(self.nombre, str(filename))

    def carrera_imagen_administrador(self):
        if not self.foto:
            return None

        imagenHTML = '<img src="/media/{0}" style="width: 75px" />'.format(
            self.foto
        )

        if ('.jpg' in imagenHTML):
            return imagenHTML.replace('.jpg', '.miniatura.jpg')
        elif ('.jpeg' in imagenHTML):
            return imagenHTML.replace('.jpeg', '.miniatura.jpeg')
        elif ('.png' in imagenHTML):
            return imagenHTML.replace('.png', '.miniatura.png')
        elif ('.gif' in imagenHTML):
            return imagenHTML.replace('.gif', '.miniatura.gif')
        else:
            return imagenHTML

    carrera_imagen_administrador.allow_tags = True

    nombre = models.CharField(max_length=50)
    foto = StdImageField(upload_to=image_path,
                         variations={'miniatura': (75, 75)}
                         )
    expositor = models.CharField(max_length=50)
    expositor_Descripcion = models.TextField()
    video = EmbedVideoField()
    video_en_vivo = EmbedVideoField(blank=True)
    imagen_en_vivo = StdImageField(upload_to=image_path,
                                   variations={'miniatura': (75, 75)}
                                   )

    def __str__(self):
        return self.nombre

apps/contacto/forms.py
# Python imports


# Django imports
from django import forms


# Local imports
from .models import Colegio


class ContactoForm(forms.ModelForm):

    class Meta:
        model = Colegio
        fields = ('nombre', 'distrito', 'telefono', 'direccion', 'asunto',)

apps/contacto/views.py
# Python imports


# Django imports
from django.views.generic import FormView


# Local imports
from .forms import ContactoForm


# Create your views here.
class ContactanosView(FormView):

    form_class = ContactoForm
    template_name = 'contacto/index.html'
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super(ContactanosView, self).form_valid(form)

apps/principal/views.py
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView

from .models import Beneficio, Carrera, Colaborador


class IndexView(TemplateView):
    template_name = 'principal/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['beneficios'] = Beneficio.objects.all()
        context['colaboradores'] = Colaborador.objects.all()
        return context


class EntrevistaView(TemplateView):
    template_name = 'principal/entrevista.html'

    def get_context_data(self, **kwargs):
        context = super(EntrevistaView, self).get_context_data(**kwargs)
        context['carreras'] = Carrera.objects.all()
        return context


class CarmenGitHubView(RedirectView):
    permanent = True
    url = 'http://carmenluyo.github.io/elige.la/'

apps/contacto/templates/contacto/index.html
{% extends 'principal/base.html' %}
{% load staticfiles %}


{% block titulo %}Formulario{% endblock %}

{% block estilos-estaticos %}
<link rel="stylesheet" href="{% static 'principal/css/font-awesome.min.css' %}" />
<link rel="stylesheet" href="{% static 'principal/css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'principal/css/estilos.css' %}">
<link rel="stylesheet" href="{% static 'contacto/css/main.css' %}">
{% endblock %}

{% block encabezado %}
<div class="fondo-menu"></div>
{% endblock %}

{% block cuerpo %}
<section>
  <div class="container">
    <div class="center-text">
      <h1>INSCRIBE TU COLEGIO</h1>
      <p style="width: 100%;">
        Haz que tu colegio sea uno de los seleccionados <br> para realizar los talleres vocacionales.
      </p>
    </div>
    <div class="row">
      <div class="col-sm-4"></div>
      <!-- FORM ============ -->
      <div class="col-sm-4">
          <form method="POST">{% csrf_token %}
              <!-- NAME -->
              <div class="form-group">
                  <label>Nombre del colegio</label>
                  <input id="id_nombre" maxlength="100" name="nombre" type="text" class="form-control" />
              </div>
              <div class="form-group">
                  <label>Distrito</label>
                  <input id="id_distrito" maxlength="100" name="distrito" type="text" class="form-control" />
              </div>
              <div class="form-group">
                  <label>Telefono del colegio (Opcional)</label>
                  <input id="id_telefono" maxlength="9" name="telefono" type="text" class="form-control" />
              </div>
              <div class="form-group">
                  <label>Direccion del colegio</label>
                  <input id="id_direccion" maxlength="100" name="direccion" type="text" class="form-control" />
              </div>
              <div class="form-group">
                <label for="">¿Por qué deberiamos ir a tu colegio?</label>
                <textarea cols="40" id="id_asunto" name="asunto" rows="10" class="form-control"></textarea>
              </div>
              <div class="form-group text-center">
                <input type="submit" class="btn btn-primary" value="Enviar" />
              </div>
          </form>
        </div>
      </div>
      <div class="col-sm-4"></div>
  </div>
</section>
{% endblock %}

apps/principal/templates/principal/base.html
{% comment %}
  Desarrollado por: Sr. Fuego
  Elige.la
{% endcomment %}

{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <title>{% block titulo %}{% endblock %} | Elige.la</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    {% block estilos-estaticos %}{% endblock %}
  </head>
  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.5";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <header>
      <nav class="navbar">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" id="logo" href="{% url 'principal:index' %}">
              <img src="{% static 'principal/img/eligela.png' %}" />
              <p>eligela</p>
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'principal:index' %}">Inicio</a></li>
              <li><a href="{% url 'principal:entrevista' %}">#eligelaEntrevista</a></li>
              <li><a href="https://medium.com/@elige.la">Blog</a></li>
              <li><a href="{% url 'contacto:index' %}">Contacto</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    {% block encabezado %}{% endblock %}
    {% block cuerpo %}{% endblock %}
    <footer>
      <div class="row">
        <a href="https://www.facebook.com/elige.la.comunidad" target="_blank" class="col-xs-6" id="eligela-facebook"><i class="fa fa-facebook fa-2x red-social-circulo"></i><div>/elige.la.comunidad</div></a>
        <a href="https://twitter.com/eligela_" target="_blank" class="col-xs-6" id="eligela-twitter"><i class="fa fa-twitter fa-2x red-social-circulo"></i><div>/eligela_</div></a>
      </div>
    </footer>
    <script src="{% static 'principal/js/jquery.js' %}"></script>
    <script src="{% static 'principal/js/bootstrap.js' %}"></script>
  </body>
</html>

apps/principal/templates/principal/entrevista.html
{% extends 'principal/base.html' %}
{% load staticfiles %}
{% load embed_video_tags %}
{% comment %}
  Desarrollado por: Sr. Fuego
  Elige.la
{% endcomment %}

{% block titulo %}Entrevista{% endblock %}

{% block estilos-estaticos %}
<link rel="stylesheet" href="{% static 'principal/css/font-awesome.min.css' %}" />
<link rel="stylesheet" href="{% static 'principal/css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'principal/css/estilos.css' %}">
{% endblock %}

{% block encabezado %}
<div class="fondo-menu"></div>
{% endblock %}

{% block cuerpo %}
  {% for carrera in carreras %}
    <div class="container">
      <div class="titulo-conferencia">
        <h2>{{ carrera.nombre }}</h2>
      </div>
      <div class="row">
        <div class="video-container col-md-8">
          {% video carrera.video as mivideo %}
            <iframe width="560" height="315" src="{{ mivideo.url }}" frameborder="0" allowfullscreen></iframe>
          {% endvideo %}
        </div>


        <div class="col-md-4">
          {# caja de twitter #}
          <a class="twitter-timeline" href="https://twitter.com/hashtag/eligelaentrevista" data-widget-id="644771400008486912">Tweets sobre #eligelaentrevista</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
          {# caja de twitter #}
        </div>
      </div>

      <div class="expositor">
        <h3>{{ carrera.expositor }}</h3>
        <img src="/media/{{ carrera.foto.miniatura }}" />
        <p>{{ carrera.expositor_Descripcion }}</p>
      </div>

      <div style="margin: 50px 40%;">
        <div class="fb-share-button" data-href="https://www.facebook.com/elige.la.comunidad" data-layout="button_count"></div>
        <div class="fb-like"></div>
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="https://twitter.com/eligela_" data-via="eligela_" data-lang="es" data-related="eligela_" style="padding-top: 50px;">Twittear</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      </div>

      <h3>En vivo</h3>
        {% if carrera.video_en_vivo %}
          {% video carrera.video_en_vivo as mivideoenvivo %}
          <div class="video-container">
            <iframe width="560" height="315" src="{{ mivideoenvivo.url }}" frameborder="0" allowfullscreen></iframe>
          </div>
          {% endvideo %}
        {% else %}
          <img src="/media/{{ carrera.imagen_en_vivo }}" width=100% />
        {% endif %}

    </div>
  {% endfor %}
{% endblock %}

apps/principal/templates/principal/index.html
{% extends 'principal/base.html' %}
{% load staticfiles %}

{% comment %}
  Desarrollado por: Sr. Fuego
  Elige.la
{% endcomment %}

{% block titulo %}Bienvenido{% endblock %}

{% block estilos-estaticos %}
<link rel="stylesheet" href="{% static 'principal/css/font-awesome.min.css' %}" />
<link rel="stylesheet" href="{% static 'principal/css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'principal/css/estilos.css' %}">
{% endblock %}

{% block encabezado %}
<div class="bg_top">
  <p>Descubre tu vocación y elige tu carrera profesional con un taller dinámico y diferente</p>
  <a href="{% url 'contacto:index' %}"><button>REGISTRA TU COLE YA</button></a>
</div>
{% endblock %}

{% block cuerpo %}
  <h2>Beneficios del taller</h2>
  <div class="row">
    {% for beneficio in beneficios %}
      <div class="col-sm-4">
        <img src="/media/{{ beneficio.imagen }}" />
        <p>{{ beneficio.descripcion }}</p>
      </div>
    {% endfor %}
  </div>
  <div id="barra-horizontal"></div>
  <h2>Con el apoyo de:</h2>
  <div class="row">
  {% for colaborador in colaboradores %}
    <a href="{{ colaborador.link }}" class="col-xs-4"><img src="/media/{{ colaborador.imagen.miniatura }}" alt={{ colaborador.nombre }} /></a>
  {% endfor %}
  </div>
{% endblock %}